### ISSUE TITLE
why not open source some channel data ?

### ISSUE THREAD

**Issue by Yuxin-Zhang-Jasmine** [VU-BEAM-Lab/ADMIRE#1]
Hello christopher, 
Thank you for your code. Your work is so cool !

I download and run it using my own dataset, but the quality of the beamformed image is not satisfying. I'm wondering if it's possible for you to open source some channel data of your work? 

And I've sent you an email for some questions about the algorithm of ADMIRE, looking forward to your reply :-) 

regards,
yuxin
yuxin.zhang@ls2n.fr

**Comment by Yuxin-Zhang-Jasmine** [comment]
Thank you christopher. I received your email and it really helps a lot ! 
The explaination of tau_n0, tau_n, and the overviw of ADMIRE is very clear.
But there are two things I still don't understand: 

1. why use the **round trip distance** to determine the bound of the stft window, and why z_distance equals to 2.*z_f.  In other words, 
why not z_distance = z_f, and 
min_travel_distance_STFT_window = params.depths_in_window(1) ;
max_travel_distance_STFT_window = params.depths_in_window(end) ; ?

 2. In the script ''**generate_modeled_signal_for_predictor.m**'', there is  stt = ((params.c) .^ 2) ./ (4 .* (pi .^ 2) .* sff);  (line86)
 However, why the numerator is not 1 but ((params.c) .^ 2) ?

Thank you in advance and best regards !
yuxin

**Comment by Yuxin-Zhang-Jasmine** [comment]
About how we apply the code of ADMIRE:

In this link here: https://drive.google.com/drive/folders/1YfA0ia4MrQvVjDNmlvmhw0gzlVLyg5CI?usp=sharing
you can find how we apply ADMIRE to two datasets (simulation and experiment) which come from https://github.com/nbottenus/REFoCUS

The original channel data downloaded from REFoCUS considers all of the elements to do receiving for each beam, so I deleted some data received by elements outside the active aperture to fit in the required format (#depth * #elements/beam * #beams) for ADMIRE. The processed channel data is fed in ADMIRE and also REFoCUS code, and the reconstructed images are compared in the pdf file which is in the same link of drive. I said our beamformed images by ADMIRE were not satisfying because from the pdf file we can see that REFoCUS gives much better image quality. I don't know if it's because the datasets themselves or other reasons, so I 'd like to use other datasets to know better about the performance of ADMIRE.

I try to create our own walked-aperture data by Field II or our ultrasound machine. But because I'm a beginner with these ways, I often meet strange problems and get stuck, like today when I tried Field II combined with USTB toolbox to do a DAS beamforming, the result is sooo wierd.  So I'm wondering if you could share us some code of simulating channel data of walked-aperture focused transmit and/or doing DAS on that?  If it's not available, just the simulated channel data you used for the benchmark in your paper(2021) can also help us a lot!

Thank you!!
best regards
yuxin

**Comment by Christopher-Khan** [comment]
Hi Yuxin. I'm going to go ahead and close this issue, since we communicated via email about the above comments. If you have any more comments, just let me know, and I'll be happy to help!

Thanks and good luck!
Christopher Khan
